runtime/src/main/scala/tailcall/runtime/transcoder/Document2Config.scala
runtime/src/test/scala/tailcall/runtime/DSLFormatSpec.scala

- refactor: clean up error handling on the CLI
- doc: add contribution guidelines
- refactor: clean up EvaluationError.scala
- refactor: use HttpAssertions to check for statuscode
- feature: show endpoint count in check and publish
- style: scalafmt
- refactor: add StatusCodeError
- refactor: add better error name
- refactor: add better error name
- refactor: add body to logs
- feat: add cache for reading blueprint and creation of interpreter
- refactor: better names
- refactor: add DataLoader.make method
- refactor: use DataLoader.make in InterpreterDataLoader
- refactor: rename file to BlueprintDataLoader
- fix: Http directive not being understood

Fix: Http directive not being detected

---

cli/src/main/scala/tailcall/cli/CommandADT.scala
cli/src/main/scala/tailcall/cli/CommandDoc.scala
cli/src/main/scala/tailcall/cli/CustomOptions.scala
cli/src/main/scala/tailcall/cli/service/CommandExecutor.scala
runtime/src/main/scala/tailcall/runtime/model/Blueprint.scala
runtime/src/main/scala/tailcall/runtime/model/Config.scala
runtime/src/main/scala/tailcall/runtime/model/UnsafeSteps.scala
runtime/src/test/scala/tailcall/runtime/ConfigSpec.scala
runtime/src/test/scala/tailcall/runtime/transcoder/ConfigSDLIdentitySpec.scala

- fix: bug in inlining scalar fields (#132)
- test: add inline tests into a suite
- refactor: add unit operator to TValid
- fix: handle required type while inlining values from a list type
- refactor: rename method on Config
- chore(deps): update dependency sbt/sbt to v1.8.3 (#133)
- Fix inline on parent resolved values (#135)
- Config input type (#138)
- refactor: drop unused field from Blueprint
- TValid Improvement (#139)
- chore(deps): update dependency dev.zio:zio-cli to v0.5.0 (#136)
- Feature: Server settings can be set via CLI (#140)
- feature: add n + 1 detection
- style: reorder methods
- feature: display n + 1 issues in the spec

Feature: Add N + 1 detection support

---

build.sbt
runtime/src/main/scala/tailcall/runtime/lambda/Lambda.scala
runtime/src/main/scala/tailcall/runtime/model/Blueprint.scala

Represents Blueprint as a scalar. This makes its much faster and easier to query and mutate.

Fix: Use Scalar for Blueprint

---

runtime/src/main/scala/tailcall/runtime/model/Path.scala
runtime/src/test/scala/tailcall/runtime/PathSpec.scala
runtime/src/test/scala/tailcall/runtime/transcoder/ConfigSDLIdentitySpec.scala

Allow additional characters in path, to be able to specify paths like
https://restcountries.com/v3.1/all
(https://datatracker.ietf.org/doc/html/rfc3986#section-2.3)

fix: unreserved chars in path segment

---

runtime/src/main/scala/tailcall/runtime/service/DataLoader.scala
runtime/src/main/scala/tailcall/runtime/service/EndpointGenerator.scala
runtime/src/main/scala/tailcall/runtime/service/EvaluationRuntime.scala
runtime/src/main/scala/tailcall/runtime/service/HttpCache.scala
runtime/src/main/scala/tailcall/runtime/service/HttpContext.scala
runtime/src/main/scala/tailcall/runtime/service/StepGenerator.scala
runtime/src/test/scala/tailcall/runtime/HttpCacheSpec.scala
server/src/main/scala/tailcall/server/GenericServer.scala

Intelligently calculate the cache headers from the downstream requests made by each query and forward the minimum to the client

better response cache headers

---

.github/workflows/benchmark.yml

This allows us to run benchmarks on a consistent hosted infrastructure. Before this change, github would run the benchmarks on shared infrastructure, and hence the performance tests would return vastly different results.

Add dedicated benchmarking infrastructure

---

src/blueprint/from_config.rs
src/config/config.rs
src/config/from_document.rs
src/config/into_document.rs
src/config/n_plus_one.rs
tests/graphql/test-modify.graphql

**Summary:**  
Instead of `Option<bool>` etc use `#[serde(default)]` to mark fields as optional with some default value.
These changes simplifies the code and prevents possible bugs when utilizing Option
Fixes #371
/claim #371
**Checklist:**

refactor: replace Option wrappers with serde(default) attribute

---

src/config/config.rs
src/config/from_document.rs
src/directive.rs
src/valid/error.rs
tests/graphql/errors/test-invalid-server.graphql
tests/graphql/errors/undeclared-type-no-base-url.graphql
tests/graphql_spec.rs

**Summary:**  
Document to Config need to show validation errors instead of converting to blueprint with default on failures
Fixes #417 
**Checklist:**

feat: errors in config.rs

---

src/blueprint/from_config.rs
src/config/config.rs
src/config/from_document.rs
src/valid/cause.rs
src/valid/valid.rs
tests/graphql/errors/test-const-with-inline.graphql
tests/graphql/errors/test-const.graphql
tests/graphql/errors/test-multiple-resolvable-directives-on-field.graphql
tests/graphql/passed/test-const-nullable.graphql
tests/graphql/passed/test-const-with-inline-with-modify-field.graphql
tests/graphql/passed/test-const.graphql

**Summary:**  
It adds `@const` directive to set const value for test and other purposes. `const` also makes sure that provided `data` conforms with the type `T`.
**Checklist:**
/claim #373

feat: add const directive

---

Cargo.lock
Cargo.toml

**Summary:**  
potential reason:
https://github.com/alexcrichton/curl-rust/issues/524#issuecomment-1702156654
I followed this sulution.
https://github.com/alexcrichton/curl-rust/issues/524#issuecomment-1703325064
ref:
https://github.com/curl/curl/commit/6ab7e19
https://github.com/rust-lang/cargo/issues/12670
https://github.com/alexcrichton/curl-rust/issues/524
**Checklist:**

fix: cargo test fail in Sonoma or later of macos

---

.github/scripts/check_if_build.sh
.github/workflows/ci.yml
Cargo.lock
Cargo.toml

**Summary:**  
1. add script file to check if the changes in ./src and "cargo.toml" "cargo.lock" "fly.toml" "DockerFile". So if changes are in tests(.rs. i.e. integration test), the build workflow can still run for the test.
2. using job condition `if` to skip `deploy` and `release` jobs.
3. add restore-keys so that even if there is a tiny change in the cache, the cache can still be used for that non-change pkg.
4. replace ::set-output name with echo "name=value" >> $GITHUB_OUTPUT. 
ref: [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
5. update the revision of sys-curl for Sonoma or later version of macos.
ref: …

CI: ignore build when no changes for executable

---

src/blueprint/blueprint.rs
src/blueprint/from_config.rs
src/config/config.rs

**Summary:**  
Vec<_> makes merging of config's error prone due to possibility of duplicates
**Checklist:**

refactor: use btreeset where duplicates are not allowed

---

install.sh

This PR fixes installing binary when version isn't specified
Current implementation was broken.

fix: install.sh

---

.github/workflows/ghcr.yml

**Summary:**  
_Build and push a Docker image to GHCR.io._
Fixes #502. Please also see https://github.com/tailcallhq/tailcallhq.github.io/pull/22 to update the [docs](https://tailcall.run/docs/guides/installation/#docker) where the Docker image is used.
When you push a new tag, say v0.13.0, the action will apply the tags `v0.13.0` and `latest` to it. Please refer to the [documentation](https://github.com/docker/metadata-action#basic).
I tested using my account so it is published at`ayewo/tailcall/tc-server:v0.13.0` but once merged, it will be published at `tailcallhq/tailcall/tc-server:v0.13.0`.
The published package:
* https://github.com/ayewo/tailcall/pkgs/container/tailcall%2Ftc-server/138387740?tag=v0.13.0
The successful job run:
* …

feat: push docker image to ghcr.io

---

.github/workflows/bot.yml

This PR adds lint:fix job that can be triggered via `ci:lint` label.
/claim #505

auto fix lint issues via CI

---

.github/workflows/ci.yml
.github/workflows/release.yml

**Summary:**  
We create a separate github action which runs only after a release is published. We also modify the original `ci` github action to remove the `deploy` step so we don't deploy on push to main
Fixes #490 
**Checklist:**

chore: run ci deploy step only on release

---

Cargo.lock
Cargo.toml
src/http/response.rs

**Summary:**  
The dep is not used in the project and can be removed
**Checklist:**

refactor: remove unused library http-cache-semantics

---

tests/http_spec.rs

**Summary:**  
I've encountered a behavior inconsistency in the `http_spec` configuration concerning the handling of assertions when the `fail` annotation is used. According to the current functionality, the tests are expected to pass when the underlying assertions fail, and they should also fail if the assertions unexpectedly pass. However, I'm observing that the tests are panicking in scenarios where they should ideally pass while using `fail` annotation.
With the `fail` annotation in the `http_spec` configuration, the expected behavior should be as follows:
* **On Assertion Failure:** The test should pass. This aligns with the intent of the `fail` annotation, where assertion failures are anticipated.
* **On Assertion Success:** If the assertion unexpectedly passes, the test should also …

Issue with `http_spec` Configuration: Tests Panic Despite `fail` Annotation

---

Cargo.lock
Cargo.toml
src/http/http_1.rs
src/http/http_2.rs
src/http/mod.rs
tests/graphql/errors/test-hostname-faliure.graphql
tests/graphql/passed/test-batching-group-by.graphql
tests/graphql/passed/test-batching.graphql
tests/http/config/graphql-dataloader-batch-keys.graphql
tests/server/config/server-start-http2.graphql
tests/server/config/server-start.graphql

- chore: install webbrowser
- chore: enable `hardened` and `disable-wsl` features
- feat: create a method to open browser
- feat: change `log_launch` to also open browser
**Summary:**  
This PR adds [webbrowser](https://github.com/amodm/webbrowser-rs) to open the default browser when the server starts.
I'm using [webbrowser](https://github.com/amodm/webbrowser-rs) instead [opener](https://github.com/Seeker14491/opener) for three main reasons:
- Option to turn off `file://` URLs, which is good for security (we only need to open `http://` and `https://`)
- Compatibility with multiple platforms
- According to them:
> **Browser guarantee** - This library guarantees that the browser is opened, even for local files - the only crate to make 
such guarantees at the time of this writing. …

Feature: open playground in the browser automatically if enabled

---

examples/.tailcallrc.graphql

Adds documentation for directives properties in .taillrc.graphql
https://github.com/tailcallhq/tailcall/assets/62795688/441b9109-e019-40dc-8a42-f52f69330585
/fixes #740
/claim #740

docs: add documentation for .tailcallrc.graphql

---

lint.sh

**Summary:**  
`bash lint.sh --mode=fix` wasn't failing when there were clippy warnings in the code, but `bash lint.sh --mode=check` was failing in that case. This pr will run clippy check after applied fix to fail the run in case there were clippy warnings. 
**Checklist:**
[documentation website]: https://github.com/tailcallhq/tailcallhq.github.io

ci: lint.sh scripts fail on warnings in fix mode

---

src/lambda/evaluation_context.rs
src/path.rs
tests/http/config/args-body.graphql
tests/http/test-params-as-body.yml

**Summary:**  
Modifies `path_string` to handle path with length 1.
Fixes #774
**Checklist:**
[documentation website]: https://github.com/tailcallhq/tailcallhq.github.io
/claim #774
/split @ologbonowiwi 30%

fix: Bug in {{args}} rendering

---

src/json/json_like.rs
src/json/json_schema.rs
src/lambda/evaluation_context.rs

**Summary:**  
Improve the performance of fn `get_path_value` for `EvaluationContext`
Based on findings found from flamegraph - instead of creating async_graphql::Name to resolve values from hashmap use &str explicitly.
Before that change:
wrk bench:
```
wrk -d 30 -t 8 -c 100 -s ci-benchmark/wrk.lua http://localhost:8000/graphql
Running 30s test @ http://localhost:8000/graphql
8 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     1.58ms    1.16ms  81.53ms   88.14%
Req/Sec     7.71k     1.16k   16.50k    92.93%
1871300 requests in 30.05s, 9.38GB read
Socket errors: connect 0, read 0, write 0, timeout 384
Requests/sec:  62269.78
Transfer/sec:    319.61MB
```
After:
wrk bench:
```
wrk -d 30 -t 8 -c 100 -s ci-benchmark/wrk.lua …
```

perf: improve performance of path_string impl for EvaluationContext

---

.github/workflows/bot.yml

**Summary:**  
currently in bot.yml we use 
```
- name: Cache Criterion Benchmarks Json
uses: actions/cache@v2
with:
path: benches/main_benchmarks.json
key: criterion_benchmarks_${{ github.sha }}
restore-keys: |
criterion_benchmarks_
```
to cache the benchmarks in json file 
so whenever we need to restore this cache we generally use the following  or the cache id  :
```
- name: Restore file
uses: actions/cache@v2
with:
path: benches/main_benchmarks.json
key: criterion_benchmarks_${{ github.event.pull_request.base.sha }}
fail-on-cache-miss: true
```
but it always restore the same json file for all the cache id' s 
thats why we were getting error in  while comparing benchmarks 
So i changed `actions/cache@v2` to `actions/cache@v3`
and everything works file 
i have created a pr to update the …

updated cache benchmarks from actions/cache@v2 to actions/cache@v3 

---

src/http/server_config.rs

**Summary:**  
Fix the problem when in config defined `hostname: "0.0.0.0"` and therefore graphql playground shows address `0.0.0.0` in the logs and open the browser on zeros ip. Instead of using broken address replace unspecified address with localhost.
**Checklist:**
[documentation website]: https://github.com/tailcallhq/tailcallhq.github.io

fix: open localhost in browser in case of using unspecified host

---

.github/workflows/bot.yml
Dockerfile
docs/guides/logging.md
src/cli/command.rs
src/cli/tc.rs

**Summary:**  
Use either `TAILCALL_LOG_LEVEL` or `TC_LOG_LEVEL` as a place to set the log level. 
Fixes #791 
/claim #791 
**Checklist:**
---- there seems to be no tests of the log level, so nothing to be updated
----- Can't find where/how. Let me know where I can make this change, if I can 
[documentation website]: https://github.com/tailcallhq/tailcallhq.github.io

feat: set the log level using env variable

---

.github/workflows/pr-convention.yml

**Summary:**  
Add support for PR Title Validation
Fixes #814 
/claim #814
**Description**
- Added `pr-convention.yml` workflow which will be triggered on each PR raised and will validate the title of the PR
- Test PRs on [ezhil56x/tailcall](https://github.com/ezhil56x/tailcall/pulls)

ci: added pr-convention workflow

---

tests/http_spec.rs

**Summary:**  
Show log info instead of error
Fixes #738
/claim #738
**Checklist:**

fix: show log info instead of error when expected failure happens

---

docs/guides/environment-variables.md
docs/guides/environmental-variables.md

**Summary:**  
This PR adds a file called `environmental-variables.md` into the `docs/guides` folder. This guide is aimed at providing the users a clear picture about the whereabouts of environmental variables and how to use them in Tailcall.
Fixes #852 
/claim #852
**Checklist:**

docs: add environmental-variables guide

---

.github/workflows/bot.yml
.github/workflows/ci-docs.yml
.github/workflows/ci.yml

- build: disable benchmarks for `docs` and `*.md` files
- build: remove spelling check from ci
Fixes #860
/claim #860
**Checklist:**

ci(workflows): avoid running Rust-related workflows for markdown-only changes

---

src/cli/error.rs
src/valid/cause.rs
src/valid/error.rs

This PR fixes validation error printing multiple times was caused by iterating twice
Before:
After:
/fixes #906
/claim #906

fix: validation error printing multiple times

---

src/try_fold.rs
src/valid/valid.rs

**Summary:**  
Fixes the problem with TryFold type that calls some of the handlers multiple times. It mostly affects conversion from config to blueprint and leads to some of handlers to set resolvers by operators to get called up to 4 times due to nested try_folds.
Right now there is no big problem in the code because most of the updates returns new instance to use instead of mutating it. But in case of mutating in such handlers it could lead to problems and unnecessary wrappers.
The problem revealed itself in the https://github.com/tailcallhq/tailcall/pull/833 and `cache` directive. So if I debug this I see Cache expression inside Cache expression because of the bug.
**Checklist:**

fix: try_fold multiple calls for the same handler

---

src/config/config.rs
tests/graphql/test-nested-input.graphql

fix: inner fields in nested input type was considered as output type

---

src/config/mod.rs
src/config/server.rs
src/config/upstream.rs

**Summary:**  
This PR splits `config::Server` and `config::Upstream` into two separate files — `config/upstream.rs` and `config/server.rs`
Fixes #1014 
**Checklist:**

refactor: split into server.rs and upstream.rs

---

.github/pull_request_template.md

**Summary:**  
Fixes 404 link in the pull request template.
**Checklist:**

chore(docs): fix 404 in docs link

---

src/blueprint/definitions.rs
src/config/from_document.rs
src/config/into_document.rs
tests/graphql/test-cache.graphql

**Summary:**  
`@cache` directives are not serialized when calling `config.to_sdl()`. This PR adds logic to `into_document.rs` to fix this.
**Checklist:**

fix(document): serialize @cache directives

---

autogen/src/gen_gql_schema.rs
autogen/src/main.rs
cloudflare/src/handle.rs
cloudflare/src/lib.rs
lint.sh

**Summary:**  
clippy was not triggered for workspace members previously
**Checklist:**

ci: enable lint check for workspace members

---

cloudflare/src/handle.rs
cloudflare/src/lib.rs
src/app_context.rs
src/cli/mod.rs
src/cli/server/server_config.rs
src/cli/tc.rs
src/config/reader.rs
src/grpc/data_loader_request.rs
src/grpc/protobuf.rs
src/grpc/request_template.rs
src/http/request_context.rs
src/lib.rs
src/target_runtime.rs
tests/graphql_spec.rs
tests/http_spec.rs
tests/server_spec.rs

**Summary:**  
Adds `TargetRuntime` struct and uses it for `ConfigReader` and `AppContext` to simplify piping.
**Checklist:**

chore: introduce and use `TargetRuntime`

---

docker.sh
testconv/src/http.rs
testconv/src/main.rs
tests/execution_spec.rs
tests/snapshots/execution_spec__graphql-dataloader-batch-keys.md_assert_0.snap

**Summary:**  
This PR fixes:
- people can't use normal cargo test harness feature flags with cargo test anymore because execution_spec would try to look up a file with it.
- prettierrc file not located leading to lots of formatting changes that are useless
- properties in `env` dancing around resulting in useless diffs
**Checklist:**

chore: various execution_spec/testconv hotfixes

---

testconv/src/main.rs

This PR fixes failing testconv on fresh clones of the repo.
**Checklist:**

fix(testconv): only convert from existing dirs

---

.prettierrc

**Summary:**  
This PR fixes the inconsistency in the rules for `devcontainer.json` between the CI and local environments.
**Checklist:**

chore(prettier): don't put trailing commas in devcontainer.json

---

Cargo.toml
cloudflare/Cargo.toml

This PR fixes `warning: profiles for the non root package will be ignored, specify profiles at the workspace root:`
Fixes #1109
/claim #1109

chore: cargo profile warning

---

.github/workflows/ci.yml

**Summary:**  
This PR is a hotfix that allows the CI to build the Lambda image.
**Checklist:**

fix(aws): prevent skipping of AWS release build

---

Cargo.lock
aws-lambda/Cargo.toml
aws-lambda/src/http.rs
aws-lambda/src/main.rs

**Summary:**  
The disparity between the `lambda_runtime` and `lambda_http` versions broke the AWS build. This PR updates `lambda_http` to fix our AWS build.
This update is made more complex by the version disparity of the `http` crate in `lambda_http` and the version of `hyper` we are using. A lot of this code is temporary and we can get rid of it once we update `hyper`. However, we cannot avoid this code altogether, since this fix is needed.
**Checklist:**

fix(aws): update lambda_http to fix AWS Lambda build

---

docker.sh

**Summary:**  
This PR adds a missing workspace member removal to `docker.sh` which fixes the docker image build in the CI.
**Checklist:**

fix(docker): fix build being broken by AWS

---

Cargo.lock
Cargo.toml
src/cli/javascript/runtime.rs

**Summary:**  
Update dependencies versions
**Checklist:**

chore: update deno_core version

---

src/config/reader.rs

chore: switch to FileIO from tokio fs

---

src/cli/update_checker.rs

Tailcall should print a warning when installed version is not the latest version (#930), but these warnings never get printed.
This pr fixes that problem (probably)

chore: fix app version warning 

---

src/lambda/cache.rs
src/lambda/modify.rs

**Summary:**  
Cache was not working because it was cleaned when updating resolvers from app_context
**Checklist:**

fix: losing cache wrapper for expr from app_context

---

Cargo.lock
Cargo.toml
cloudflare/Cargo.toml

chore: move `async-graphql*` dependency link to tailcallhq

---

src/blueprint/schema.rs
src/config/config_module.rs
tests/core/snapshots/test-scalars.md_4.snap
tests/core/snapshots/test-scalars.md_5.snap
tests/core/snapshots/test-scalars.md_7.snap
tests/core/snapshots/test-scalars.md_9.snap
tests/core/snapshots/test-scalars.md_client.snap
tests/core/snapshots/test-scalars.md_merged.snap
tests/execution/test-scalars.md

**Summary:**  
Using custom scalar type was returning `{}` instead of the value itself
**Checklist:**

fix(scalar): custom scalars should return data as is

---

generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/config/upstream.rs

fix: making `dedupe` nullable in `.tailcallrc.graphql`

---

Cargo.lock
Cargo.toml
src/core/graphql/request_template.rs
src/core/grpc/data_loader_request.rs
src/core/grpc/request_template.rs
src/core/http/data_loader_request.rs
src/core/http/request_template.rs
tailcall-hasher/Cargo.toml
tailcall-hasher/src/lib.rs

fix: replacing `DefaultHasher`

---

.github/workflows/nginx-benchmark.yml
ci-benchmark/nginx-benchmark.graphql
ci-benchmark/nginx.conf
npm/package-lock.json

chore: adding nginx benchmark in ci

---

.github/workflows/ci.yml

**Summary:**  
Updated the CI to build Tailcall on all supported platforms without any feature flags
- Unsupported platforms
Fixes #1869 
/claim #1869 
**Checklist:**

fix:  Enable JS build for all architecture

---

Cargo.lock
Cargo.toml
benches/impl_path_string_for_evaluation_context.rs
src/cli/runtime/http.rs
src/core/runtime.rs
tailcall-http-cache/Cargo.toml
tailcall-http-cache/src/http_cache_manager.rs
tailcall-http-cache/src/lib.rs
tests/server_spec.rs

**Summary:**  
- created separate workspace, tailcall-http-cache which contains the optimised cache manager.
- bench results:
before:   [38.054 µs 38.204 µs 38.428 µs]
after:      [18.419 µs 18.432 µs 18.449 µs]
performance improvement : 51%.
Related #1852
**Checklist:**

perf: improve http cache performance

---

src/core/config/config.rs

**Summary:**  
- Adds a simple check to know if the node was visited before 
Fixes #2106 
**Checklist:**

fix(config): overflow issue in get_all_used_type_names in case of cyclic type

---

Cargo.toml
src/core/ir/mod.rs

**Summary:**  
Just a small change in Display implementation for IR that is now possible with latest version of `strum_macros`
**Checklist:**

refactor: use display macro instead of manual implementation

---

src/core/ir/jit/model.rs
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__default_value.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__from_document.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__multiple_operations.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_mutation.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_query.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__variables.snap

ext of: #2105 and hence #2090
**Description**
Currently while creating/reading store, we need to iterate over Vec<Field<Children>> but the vector might contain a copy of child nodes at its root level. This change makes sure that proper tree is created which contains only the root nodes at root level.

chore(into_children): avoid having children as root nodes

---

.github/workflows/ci.yml
npm/gen-root.ts
src/core/blueprint/blueprint.rs

fix: better package names

---

generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/core/blueprint/server.rs
src/core/blueprint/upstream.rs
src/core/config/server.rs
src/core/config/upstream.rs
src/core/http/request_handler.rs
src/core/ir/io.rs
tests/core/snapshots/async-cache-enable-multiple-resolvers.md_merged.snap
tests/core/snapshots/async-cache-enabled.md_merged.snap
tests/core/snapshots/async-cache-global.md_merged.snap
tests/core/snapshots/async-cache-inflight-request.md_merged.snap
tests/core/snapshots/dedupe_batch_query_execution.md_merged.snap
tests/execution/async-cache-enable-multiple-resolvers.md
tests/execution/async-cache-enabled.md
tests/execution/async-cache-global.md
tests/execution/async-cache-inflight-request.md
tests/execution/dedupe_batch_query_execution.md

**Summary:**  
- Removes batch_execution field from Server config, dedupe_in_flight and dedupe fields from Upstream.
- Adds dedupe to Server config 
- Refactor request_handler.rs and io.rs to use the new dedupe defined in Server config  
Fixes #2182
**Checklist:**

fix: dedupe dedupe settings

---

src/core/config/transformer/snapshots/tailcall__core__config__transformer__type_name_generator__test__type_name_generator.snap
src/core/config/transformer/type_name_generator.rs
tailcall-fixtures/fixtures/configs/name-generation.graphql

**Summary:**  
- This PR addresses an issue where singular and plural forms of candidates were not consistently recognized by the filtering logic.
- This PR adds the processed candidate into set and processes every candidate and then checks in set for existence.
**Checklist:**

fix: handle plural singular type name as one.

---

src/core/data_loader/dedupe.rs
src/core/ir/io.rs

chore: remove unnecessary boxing

---

Cargo.toml
src/cli/runtime/file.rs

Fixes #2103
/claim 2103
**Reason**
`tempfile` crate tries to create a temporary file, and the test used to write and read content from the temp file, but sometimes it's unable to create/retain the temporary file's content which leads to the failure in test

chore: remove failing test

---

src/core/blueprint/dynamic_value.rs
src/core/ir/jit/synth.rs
src/core/ir/model.rs
src/core/serde_value_ext.rs

refactor: make DynamicValue polymorphic

---

Cargo.lock
Cargo.toml
benches/handle_request_bench.rs
src/cli/server/http_server.rs
src/cli/tc.rs
src/core/blueprint/auth.rs
src/core/blueprint/definitions.rs
src/core/blueprint/operators/call.rs
src/core/blueprint/operators/grpc.rs
src/core/blueprint/operators/js.rs
src/core/blueprint/operators/protected.rs
src/core/blueprint/server.rs
src/core/blueprint/upstream.rs
src/core/config/config_module.rs
src/core/config/into_document.rs
src/core/config/reader.rs
src/core/config/transformer/ambiguous_type.rs
src/core/generator/generator.rs
src/core/generator/tests/json_to_config_spec.rs
src/core/grpc/data_loader_request.rs
src/core/grpc/protobuf.rs
src/core/grpc/request_template.rs
tailcall-aws-lambda/src/main.rs
tests/core/parse.rs

**Summary:**  
- Refactor config module to use Derive getters
Fixes #2256
**Checklist:**
- [] I have added relevant unit & integration tests.
- [] I have updated the [documentation] accordingly.

chore: dropped pub fields from config module

---

src/core/config/config.rs
src/core/generator/from_proto.rs
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__from_proto.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__movies.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__oneof_types.snap
src/core/grpc/protobuf.rs
src/core/json/json_schema.rs
tailcall-fixtures/fixtures/protobuf/oneof.proto
tests/core/snapshots/grpc-oneof.md_0.snap
tests/core/snapshots/grpc-oneof.md_client.snap
tests/core/snapshots/grpc-oneof.md_merged.snap
tests/execution/grpc-oneof.md

**Summary:**  
Fixes #1912 
**Checklist:**

feat(grpc): generate union types for oneof protobuf

---

Cargo.lock

Reverts tailcallhq/tailcall#2266

Revert "fix(deps): update rust crate mimalloc to v0.1.43"

---

src/cli/generator/config.rs
src/core/config/transformer/preset.rs
src/core/resource_reader.rs

chore: improve test coverage in cli config

---

Cargo.lock
generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/core/blueprint/mustache.rs
src/core/blueprint/operators/grpc.rs
src/core/config/config.rs
src/core/generator/from_proto.rs
src/core/grpc/request_template.rs
src/core/helpers/body.rs
src/core/proto_reader/fetch.rs
tests/core/snapshots/grpc-json.md_0.snap
tests/core/snapshots/grpc-json.md_1.snap
tests/core/snapshots/grpc-json.md_2.snap
tests/core/snapshots/grpc-json.md_client.snap
tests/core/snapshots/grpc-json.md_merged.snap
tests/execution/grpc-json.md

fix(grpc): allow users to pass value along with mustache template

---

.github/labels.json
.github/workflows/benchmark.yml
.github/workflows/benchmark_pr_run.yml
.github/workflows/test-jit.yml

ci: run jit tests only when pr label is present

---

src/core/blueprint/operators/graphql.rs
tests/core/snapshots/related-fields-recursive.md_client.snap
tests/core/snapshots/related-fields-recursive.md_merged.snap
tests/execution/related-fields-recursive.md

fix: recursive types on `@graphql` directive

---

src/core/generator/json/http_directive_generator.rs

**Summary:**  
Enable Tailcall to correctly parse UUID path arguments
Fixes https://github.com/tailcallhq/tailcall/issues/2563
**Checklist:**
/claim #2563

fix(gen): Correctly parse UUID as path argument

---

generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/core/blueprint/operators/http.rs
src/core/config/config.rs
src/core/mustache/model.rs
tests/core/snapshots/test-http-batchKey.md_merged.snap
tests/execution/test-http-batchKey.md

**Summary:**  
Fix documentation and test correctness to prevent misleading of users.
**Checklist:**

fix: query parameter selection when `batchKey` is used

---

src/cli/generator/config.rs

fix: add deny_unknown_fields to nested structs

---

src/cli/telemetry.rs

**Summary:**  
- When telemetry is enabled, we configure tracing to send all tracing events to the tracing service. This pull request introduces an additional layer to the tracing setup, allowing us to both log events to the CLI and send them to the tracing service simultaneously.
**Checklist:**

fix: add CLI layer to telemetry tracing

---

src/cli/generator/config.rs
src/cli/llm/infer_type_name.rs
src/core/blueprint/dynamic_value.rs
src/core/blueprint/operators/http.rs
src/core/config/apollo.rs
src/core/config/telemetry.rs
src/core/graphql/request_template.rs
src/core/grpc/request_template.rs
src/core/helpers/body.rs
src/core/helpers/headers.rs
src/core/helpers/url.rs
src/core/http/request_template.rs
src/core/mustache/eval.rs
src/core/mustache/parse.rs
src/core/mustache/template_string.rs
src/core/proto_reader/fetch.rs
tests/expression_spec.rs

chore(2727):  drop Result from Mustache::parse

---

src/cli/generator/config.rs
tests/cli/fixtures/generator/gen_deezer.md
tests/cli/fixtures/generator/gen_json_proto_mix_config.md
tests/cli/fixtures/generator/gen_jsonplaceholder.md
tests/cli/gen.rs
tests/cli/parser.rs

(ext of https://github.com/tailcallhq/tailcall/pull/2657)

chore: convert cli tests to md

---

src/core/blueprint/blueprint.rs
src/core/jit/synth/synth.rs
tests/core/snapshots/test-required-fields.md_0.snap
tests/core/snapshots/test-required-fields.md_1.snap
tests/core/snapshots/test-required-fields.md_10.snap
tests/core/snapshots/test-required-fields.md_11.snap
tests/core/snapshots/test-required-fields.md_12.snap
tests/core/snapshots/test-required-fields.md_13.snap
tests/core/snapshots/test-required-fields.md_14.snap
tests/core/snapshots/test-required-fields.md_15.snap
tests/core/snapshots/test-required-fields.md_16.snap
tests/core/snapshots/test-required-fields.md_17.snap
tests/core/snapshots/test-required-fields.md_18.snap
tests/core/snapshots/test-required-fields.md_19.snap
tests/core/snapshots/test-required-fields.md_2.snap
tests/core/snapshots/test-required-fields.md_20.snap
tests/core/snapshots/test-required-fields.md_21.snap
tests/core/snapshots/test-required-fields.md_3.snap
tests/core/snapshots/test-required-fields.md_4.snap
tests/core/snapshots/test-required-fields.md_5.snap
tests/core/snapshots/test-required-fields.md_6.snap
tests/core/snapshots/test-required-fields.md_7.snap
tests/core/snapshots/test-required-fields.md_8.snap
tests/core/snapshots/test-required-fields.md_9.snap
tests/core/snapshots/test-required-fields.md_client.snap
tests/core/snapshots/test-required-fields.md_merged.snap
tests/execution/test-required-fields.md

**Summary:**  
Fix validation of required fields to cover edge cases for the JIT module
Remember to test it with `cargo test --features force_jit`
**Checklist:**

fix(jit): raise validation error for required fields

---

src/core/jit/synth/synth.rs
tests/core/snapshots/test-required-fields.md_13.snap
tests/core/snapshots/test-required-fields.md_17.snap
tests/core/snapshots/test-required-fields.md_21.snap
tests/core/snapshots/test-required-fields.md_9.snap
tests/core/snapshots/test-required-fields.md_merged.snap
tests/execution/test-required-fields.md

fix(jit): error handling for lists in JIT

---

.github/workflows/ci.yml
tailcall-tracker/src/tracker.rs

fix(2777): use option_env for trackers

---

src/core/ir/discriminator.rs
src/core/jit/common/jp.rs
src/core/jit/exec.rs
src/core/jit/synth/synth.rs
src/core/json/borrow.rs
src/core/json/graphql.rs
src/core/json/json_like.rs
src/core/json/serde.rs
src/core/scalar.rs

**Summary:**  
Simplify JsonLike associated type constraints according to `TODO` in the code. This is doable after serde_json_borrow update https://github.com/PSeitz/serde_json_borrow/pull/19
**Checklist:**

refactor: simplify json_like trait

---

src/cli/javascript/runtime.rs

fix: `cargo build` throwing fallback error

---

generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/core/config/link.rs
src/core/generator/generator.rs
src/core/grpc/data_loader_request.rs
src/core/grpc/protobuf.rs
src/core/grpc/request_template.rs
tests/core/snapshots/test-link-support.md_client.snap
tests/core/snapshots/test-link-support.md_merged.snap
tests/execution/test-link-support.md

chore(link): add `meta` support

---

Cargo.lock
examples/lint.sh
tailcall-tracker/Cargo.toml

fix(deps): remove unused openssl

---

ci-benchmark/benchmark.graphql
ci-benchmark/nginx-benchmark.graphql
src/core/jit/builder.rs
src/core/jit/model.rs
src/core/jit/synth/synth.rs
src/core/json/borrow.rs
src/core/json/graphql.rs
src/core/json/json_like.rs
src/core/json/serde.rs

perf: small improvements in Synth

---

Cargo.lock
Cargo.toml

**Summary:**  
Remove `from_vec` column in the base [pr](https://github.com/tailcallhq/tailcall/pull/3073#issuecomment-2438984363) with reported flamegraph time around 1%
**Checklist:**

perf: strip extra iteration when creating serde_json_borrow::Value

---

src/core/jit/graphql_executor.rs
src/core/jit/model.rs
src/core/jit/request.rs
src/core/jit/transform/check_cache.rs
src/core/jit/transform/input_resolver.rs
src/core/jit/transform/mod.rs

fix: dedupe operations that are cacheable

---

.github/workflows/build_matrix.yml

**Summary:**  
[Build fails](https://github.com/tailcallhq/tailcall/actions/runs/11868699676/job/33078485494) of rquickjs were caused by the update of github windows runners. For passing runs the Runner Image Version is older. Because of this difference there are still some ci runs that passing and failing depending on the exact runner that pick up the workflow.
**Another way to fix** this is to update rquickjs by https://github.com/tailcallhq/tailcall/pull/3112 so we can merge any of this prs
**Checklist:**

ci: use windows-2019 runner to fix windows builds of rquickjs

---

Cargo.lock
Cargo.toml
src/cli/generator/generator.rs
src/cli/tc/init.rs
src/core/blueprint/operators/resolver.rs
src/core/config/config.rs
src/core/merge_right.rs
tests/cli/parser.rs
tests/core/parse.rs

[serde_yaml](https://github.com/dtolnay/serde-yaml) is deprecated and not maintained anymore. The [serde_yaml_ng](https://github.com/acatton/serde-yaml-ng) is the fork of the original repo
**Checklist:**

chore: migrate to serde_yaml_ng instead of serde_yaml

---

src/cli/generator/config.rs
src/cli/generator/generator.rs
src/core/config/reader.rs
src/core/proto_reader/reader.rs
tailcall-fixtures/fixtures/protobuf/news_proto_paths.proto
tests/cli/fixtures/generator/gen_proto_with_proto_paths_config.md
tests/cli/snapshots/cli_spec__test__generator_spec__tests__cli__fixtures__generator__gen_proto_with_proto_paths_config.md.snap

**Summary:**  
Currently, when using the `tailcall gen` command to process proto files, the import path is fixed to a relative path, but in the [protobuf import syntax](https://protobuf.dev/programming-guides/proto3/#importing), you can specify the path to find the dependency using the `-I/--proto_path` flag. So, most proto projects are currently organized in this way, and I think we also need to support it.
```jsonc
{
"inputs": [
{
"proto": {
"src": "./proto/apps/mian.proto",
"url": "http://localhost:8080",
// new params
"protoPaths": ["./proto/apps"]
}
}
],
"preset": {
"mergeType": 1.0
},
"output": {
"path": "./output/main.graphql",
"format": "graphQL"
},
"schema": {
"query": "Query"
}
}
```
None
**Checklist:**
[documentation]: …

feat(gen): support proto_paths for gen graphql through proto file

---

src/core/blueprint/error.rs
src/core/blueprint/operators/http.rs
tests/core/snapshots/batching-validation.md_error.snap
tests/core/snapshots/test-batch-operator-post.md_error.snap
tests/execution/batching-validation.md

fix: add validation for batchKey requiring either body or query parameters

---

generated/.tailcallrc.schema.json
src/core/config/directives/link.rs
src/core/config/reader.rs
src/core/generator/generator.rs
src/core/grpc/data_loader_request.rs
src/core/grpc/protobuf.rs
src/core/grpc/request_template.rs

**Summary:**  
Previously, this [pr[3206]](https://github.com/tailcallhq/tailcall/pull/3206) only processed the `proto_paths` during gen, but when using `tailcall start`, there will still be path problems, so it is necessary to save the` proto_paths` information on the link to ensure that the path can be processed correctly during `tailcall start`.
Config:
```json
{
"inputs": [
{
"proto": {
"src": "news.proto",
"url": "http://localhost:50051",
"protoPaths": ["tailcall-fixtures/fixtures/protobuf"]
}
}
],
...
}
```
Output:
```graphql
schema
@server
@upstream
@link(
src: "news.proto"
proto_paths: ["tailcall-fixtures/fixtures/protobuf"]
type: Protobuf
) {
query: Query
}
...
```
None
**Checklist:**
[documentation]: …

feat(link): add `proto_paths` support

---

benches/handle_request_bench.rs
generated/.tailcallrc.schema.json
src/core/blueprint/server.rs
src/core/config/directives/server.rs
src/core/http/request_handler.rs
src/core/jit/builder.rs
src/core/jit/fixtures/jp.rs
src/core/jit/graphql_executor.rs
src/core/jit/request.rs
src/core/jit/synth/synth.rs
tests/core/parse.rs
tests/core/snapshots/test-enable-jit.md_merged.snap
tests/core/snapshots/test-required-fields.md_merged.snap

**Summary:**  
Ignore `enableJIT` option and use only the JIT engine to execute queries. It's still possible to define this in the config but it won't affect anything.
This is an initial step to drop async_graphql engine and more work should be done:
- rest api uses async_graphql
- introspection is implemented only by async_graphql
Fixes #3128
**Checklist:**

refactor: drop async_graphql engine from executing queries

---

.github/workflows/benchmark_comment.yml
.github/workflows/benchmark_pr_track.yml
.github/workflows/build-website.yml
.github/workflows/build_matrix.yml
.github/workflows/ci.yml
.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/pr-convention.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/spell-check.yml
.github/workflows/stale.yml

Reverts tailcallhq/tailcall#3194

Revert "chore: Migrate workflows to Blacksmith"

---

Cargo.lock
Cargo.toml
src/core/document.rs

**Summary:**  
This PR integrates the `unicode-segmentation` crate to address issues related to UTF-8 character boundaries in the `LineBreaker` struct. The changes ensure that string documentation is formatted safely without encountering byte index errors. The code now correctly iterates over grapheme clusters, thus maintaining valid character boundaries during string manipulation.
Before the change, the added test case causes a panic.
N/A
**Checklist:**

fix(core): Address UTF-8 character boundary issues in LineBreaker

---

src/core/blueprint/index.rs
src/core/jit/builder.rs
src/core/jit/model.rs
src/core/jit/transform/graphql.rs
src/core/jit/transform/input_resolver.rs
tests/core/snapshots/graphql-with-fragments.md_0.snap
tests/core/snapshots/graphql-with-fragments.md_client.snap
tests/core/snapshots/graphql-with-fragments.md_merged.snap
tests/execution/graphql-with-fragments.md

**Summary:**  
This PR is created to be able to query interfaces with fragments
Fixes #3232
**Checklist:**

fix: query interface with fragments

---

src/core/http/request_handler.rs
tests/core/snapshots/content-type-graphql.md_0.snap
tests/core/snapshots/content-type-graphql.md_client.snap
tests/core/snapshots/content-type-graphql.md_merged.snap
tests/core/spec.rs
tests/execution/content-type-graphql.md

**Summary:**  
In this PR we will accept queries in the format of content-type: application/graphql
**Checklist:**

feat: accept queries in the format of application/graphql

---

src/core/generator/proto/connect_rpc.rs
tests/cli/snapshots/cli_spec__test__generator_spec__tests__cli__fixtures__generator__proto-connect-rpc.md.snap

**Summary:**  
When using [fauxrpc]（ https://github.com/sudorandom/fauxrpc ）When calling as a connectRPC Server service, it was found that the request would be 404. After debugging, it was discovered that some connectRPC servers had done header validation and needed to pass the 'Connect Protocol Version' header for validation to comply with connect related specifications.
related link: https://connectrpc.com/docs/protocol/#unary-request
The Connect-Protocol-Version header distinguishes unary Connect RPC traffic from other requests that may use the same Content-Type. (In the future, it may also be used to support revisions to this protocol.) Clients, especially generated clients, should send this header.
Servers and proxies may reject traffic without this header with an HTTP status code of …

fix(connectRPC): add Connect-Protocol-Version header to gRPC requests

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
tailcall-aws-lambda/Cargo.toml

This PR adds musl support to the CI workflow, enabling proper AWS Lambda deployments with the required Linux environment.
AWS Lambda runs on Amazon Linux, which benefits from binaries built with musl libc for better compatibility and performance. This change ensures our Lambda builds are properly configured with the appropriate target architecture.
The implementation includes two key changes to the CI workflow:
1. Installing `musl-tools` package in the build environment
2. Configuring the Rust toolchain to include the `x86_64-unknown-linux-musl` target
These changes ensure that AWS Lambda builds use the appropriate libc implementation, which is critical for proper functioning in the Lambda environment.
The changes have been tested by verifying that the CI workflow executes successfully …

fix: add musl support for AWS Lambda builds

---

src/core/config/config_module/fixtures/upstream-allowed-headers-1.graphql
src/core/config/config_module/fixtures/upstream-allowed-headers-2.graphql
src/core/config/config_module/merge.rs
src/core/mustache/parse.rs
tests/core/snapshots/test-upstream-headers.md_client.snap
tests/core/snapshots/test-upstream-headers.md_merged.snap
tests/execution/test-upstream-headers.md

This PR addresses two related issues:
1. Fixed the propagation of allowedHeaders directive from GraphQL schema to request handler
2. Fixed the handling of header names containing hyphens in @expr directives
Fixes #3381
The first issue was in the Cache.unify method in config_module/merge.rs where the upstream field (containing allowed_headers) from the second config was being ignored during merging. The fix modifies this method to properly merge the upstream fields from both configs. When merging, we now ensure that if the second config has allowed_headers set, they are preserved in the merged result. This ensures that headers specified in the GraphQL schema's @upstream directive are correctly propagated to the request handler.
Added a comprehensive unit test that verifies the …

fix(core): preserve allowedHeaders and fix hyphenated header names
