build.sbt
project/plugins.sbt

chore: add scoverage

---

build.sbt
server/src/main/scala/tailcall/server/AdminGraphQL.scala

Reverts tailcallhq/monotail#96

Revert "chore(deps): update calibanversion to v2.1.0"

---

runtime/src/main/scala/tailcall/runtime/internal/TValid.scala

- fix: bug in inlining scalar fields (#132)
- test: add inline tests into a suite
- refactor: add unit operator to TValid
- fix: handle required type while inlining values from a list type
- refactor: rename method on Config
- chore(deps): update dependency sbt/sbt to v1.8.3 (#133)
- Fix inline on parent resolved values (#135)
- Config input type (#138)
- feature: enhance TValid

Feature: TValid new operators

---

registry/src/main/scala/tailcall/registry/MemoryRegistry.scala
registry/src/test/scala/tailcall/registry/SchemaRegistrySpec.scala

fix duplicate sha getting published in memory registry

---

runtime/src/main/scala/tailcall/runtime/transcoder/Config2Blueprint.scala
runtime/src/test/scala/tailcall/runtime/transcoder/Config2BlueprintSpec.scala

compiler error on modifying inherited fields

---

runtime/src/main/scala/tailcall/runtime/model/Endpoint.scala
runtime/src/test/scala/tailcall/runtime/EndpointSpec.scala

fix not-found query-param

---

runtime/src/main/scala/tailcall/runtime/model/Path.scala
runtime/src/main/scala/tailcall/runtime/transcoder/Config2Blueprint.scala

base url trimming fix

---

runtime/src/main/scala/tailcall/runtime/http/HttpClient.scala
runtime/src/main/scala/tailcall/runtime/service/DataLoader.scala
runtime/src/test/scala/tailcall/runtime/internal/JSONPlaceholderClient.scala
server/src/main/scala/tailcall/server/GraphQLConfig.scala
server/src/main/scala/tailcall/server/Main.scala

configure allowed headers via server CLI

---

runtime/src/main/scala/tailcall/runtime/model/Config.scala
runtime/src/main/scala/tailcall/runtime/model/Endpoint.scala
runtime/src/main/scala/tailcall/runtime/model/UnsafeSteps.scala
runtime/src/main/scala/tailcall/runtime/transcoder/Config2Blueprint.scala
runtime/src/test/resources/tailcall/runtime/graphql/test-http-headers.graphql

support custom headers via http directives

---

runtime/src/main/scala/tailcall/runtime/model/Blueprint.scala
runtime/src/main/scala/tailcall/runtime/model/Config.scala
runtime/src/main/scala/tailcall/runtime/transcoder/Blueprint2Document.scala
runtime/src/main/scala/tailcall/runtime/transcoder/Config2Blueprint.scala
runtime/src/main/scala/tailcall/runtime/transcoder/Config2Document.scala
runtime/src/main/scala/tailcall/runtime/transcoder/Document2Config.scala
runtime/src/test/resources/tailcall/runtime/graphql/test-union.graphql

- test add test for union
- add union support for configs
- feature: add support for unions

add support for unions

---

runtime/src/main/scala/tailcall/runtime/model/Endpoint.scala
runtime/src/main/scala/tailcall/runtime/model/Path.scala
runtime/src/test/scala/tailcall/runtime/PathSpec.scala

This makes the endpoints not depend on a mustache engine to evaluate the URLs

remove mustache from Path

---

registry/src/main/scala/tailcall/registry/InterpreterRegistry.scala
server/src/main/scala/tailcall/server/GraphQLConfig.scala
server/src/main/scala/tailcall/server/Main.scala

add static configs via server

---

tailcall/src/main/scala/tailcall/cli/CommandDoc.scala

Replaces the `tailcall cli` server command with `tailcall start` and takes in the config file path as an argument instead of a CustomOption

refactor: server start command

---

Cargo.lock
Cargo.toml
src/cli/tc.rs
src/main.rs

@tusharmath
This is my first PR in Rust :) so please let me know if I need to make any changes.
/claim #333

Fix: validation should fail with non-zero exit code.

---

src/cli/fmt.rs

Before and after
/claim #343 
fixes #343

fix N+1 formatting

---

src/mustache.rs

test: mustache with mixed literal and template

---

src/config/n_plus_one.rs

fix: fix false-positive case for n + 1 checker

---

src/blueprint/into_schema.rs
src/document.rs
tests/graphql/test-description-many.graphql
tests/graphql/test-query-documentation.graphql

fix: docs trim from schema

---

src/blueprint/from_config.rs
tests/graphql/errors/test-http-with-inline.graphql
tests/graphql/errors/test-inline.graphql
tests/graphql/inline-many-list.graphql
tests/graphql/inline-many.graphql
tests/graphql/passed/test-inline-field.graphql
tests/graphql/passed/test-inline-modify-field.graphql
tests/graphql/passed/test-resolved-by-parent.graphql

fix: inline operator

---

Cargo.lock
Cargo.toml
src/cli/command.rs
src/cli/tc.rs
src/http/client.rs
src/http/server.rs

**Summary:**  
Enable logging of client request and server start
fixes #420 
**Checklist:**

feat: logging

---

.github/workflows/ci.yml

**Summary:**  
- Changes the order of steps running according:
- Build -> Test -> Code Coverage -> fmt -> Lint
Fixes #394 
/claim #394
**Checklist:**

Update order of steps in GH

---

src/blueprint/from_config.rs
src/config/config.rs
tests/graphql/passed/test-resolve-with-vars.graphql
tests/graphql/passed/test-with-args.graphql
tests/graphql/test-http-headers.graphql
tests/graphql/test-http-tmpl.graphql

refactor: key values

---

.github/workflows/ci.yml
.github/workflows/stale.yml

add health bot

---

.github/contributing.md
.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/homebrew.yml
.github/workflows/stale.yml

**Summary:**  
_Made the job names consistent in CI by using title case through out._
Fixes #435  
**Checklist:**

chore: use title case for job names in CI

---

src/blueprint/into_schema.rs

performance: minor optimisation

---

src/blueprint/from_config.rs
tests/graphql/errors/test-restricted-route.graphql
tests/graphql/errors/test-restricted-route=case.graphql

Fixes #349 
**Checklist:**
/claim #349

fix: restricted url for graphiQL

---

Dockerfile

**Summary:**  
Deployment failure due to movement of config files
**Checklist:**

fix: deploy

---

benches/impl_path_string_for_evaluation_context.rs
src/http/request_context.rs
src/http/server.rs
src/lambda/expression.rs

fix: cache control headers

---

src/config/into_document.rs
tests/graphql/test-const.graphql

**Summary:**  
const resolver getting lost in identity test
**Checklist:**

fix: info loss in const serialisation

---

tests/graphql/merge/test-merge-server-sdl.graphql
tests/graphql_spec.rs

refactor: prerequisite to test multi sdl

---

benches/data_loader_bench.rs
src/blueprint/blueprint.rs
src/config/config.rs
src/config/server.rs
src/http/data_loader.rs
src/http/data_loader_request.rs
src/http/server.rs
tests/graphql/merge/test-conflict-allowed-headers.graphql
tests/graphql/merge/test-conflict-vars.graphql
tests/graphql/merge/test-enum-merge.graphql
tests/graphql/merge/test-merge-batch.graphql
tests/graphql/merge/test-merge-nested.graphql
tests/graphql/merge/test-merge-query.graphql
tests/graphql/merge/test-merge-union.graphql
tests/graphql/merge/test-server-base-types.graphql
tests/graphql/test-union.graphql
tests/graphql_spec.rs

feat: merge right on config

---

.gitignore
examples/jsonplaceholder_batch.graphql
src/cli/command.rs
src/cli/tc.rs
src/config/config.rs
src/http/server.rs
tests/graphql_spec.rs

feature: load multiple configs via CLI

---

examples/.tailcallrc.graphql
examples/jsonplaceholder.graphql
src/blueprint/blueprint.rs
src/config/server.rs
src/http/server.rs
tests/graphql/errors/test-hostname-faliure.graphql
tests/graphql_mock/test-custom-headers.graphql

feat: hostname config in server

---

benches/impl_path_string_for_evaluation_context.rs
examples/jsonplaceholder_batch.graphql
src/blueprint/blueprint.rs
src/blueprint/from_config.rs
src/blueprint/mod.rs
src/blueprint/server.rs
src/cli/tc.rs
src/http/client.rs
src/http/request_context.rs
src/http/server.rs
src/http/server_context.rs
src/lambda/expression.rs
tests/graphql_spec.rs

refactor: use blueprint server throughout

---

src/blueprint/from_config.rs
tests/graphql/passed/test-batching-default.graphql

refactor: use default batch settings if group_by is used

---

tests/graphql/errors/test-all-blueprint-errors.graphql

- fixes #503
**Summary:**  
Fixes #503 
/claim #503
**Checklist:**

fix(blueprint validation): validate component using `validate_both`

---

src/blueprint/blueprint.rs
src/blueprint/from_config.rs
src/blueprint/server.rs
src/try_fold.rs
src/valid/valid.rs

From config improvements

---

src/blueprint/blueprint.rs
src/blueprint/from_config.rs
src/blueprint/server.rs
src/try_fold.rs

**Summary:**  
refactor `to_field` in `from_config.rs`
**Checklist:**

refactor to_field

---

.github/workflows/ci.yml
.gitignore
npm/generate-root.js
npm/generate.js
npm/package-lock.json
npm/package.json

Publish Tailcall on NPM

---

.github/workflows/ci.yml
npm/generate-root.js
npm/generate.js

fix: npm version

---

src/blueprint/from_config.rs

fix: Batch with delay regression

---

npm/generate-root.js
npm/generate.js
npm/package.json

Adds metadata to npm packages including README
/claim #586
fixes #586

add metadata to npm packages

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
npm/generate.js

test: windows build

---

Cargo.lock
Cargo.toml
src/blueprint/from_config.rs
src/config/config.rs
src/config/from_document.rs
src/config/into_document.rs
src/directive.rs
src/http/server_context.rs
src/lambda/expression.rs
src/lambda/lambda.rs
src/lambda/mod.rs
src/valid/valid.rs

Refactor: Expression

---

examples/jsonplaceholder.json
examples/jsonplaceholder.yml
src/config/config.rs

Add `upstream` in `json` and `yml` example files. Add default for `added_fields` in config.rs
Fixes #599 
**Checklist:**

added_fields default, fix json,yml examples

---

src/json/json_schema.rs
tests/graphql/errors/test-const.graphql

**Summary:**  
Added the field name to trace during non-nullable validation
Fixes #638 
/claim #638 
**Checklist:**

fix: incomplete trace during const schema validation

---

.github/contributing.md

**Summary:**  
Updated development setup steps to include nightly toolchain and Prettier as they used for linting
**Checklist:**

Updated development setup steps

---

src/cli/tc.rs

**Summary:**  
Added N+1 check to start command at INFO log level
Fixes #637 
/claim #637 
**Checklist:**

Added N+1 check to start command at INFO log level

---

npm/gen-root.ts

Integrated scarf sdk

---

src/cli/tc.rs
src/http/server.rs
src/main.rs

fix: error display for address already in  use

---

npm/gen.ts

Fix windows npm installation issue
fixes #647

fix: npm release issue with windows

---

Cargo.toml
README.md
tests/http/request-to-upstream-batching.yml

**Summary:**  
Update async-graphql minimum version to include the fix to process batch requests concurrently
https://github.com/async-graphql/async-graphql/pull/1420
Release 6.0.11: https://github.com/async-graphql/async-graphql/commit/9086ca7ef0bf89723bbfe6d054e7f086b0b1cbf0
- [] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.
**Checklist:**

Test for graphql batch request to upstream batched request

---

src/async_graphql_hyper.rs
src/http/mod.rs
src/http/request_context.rs
src/http/request_handler.rs
src/lambda/expression.rs
tests/http/cache-control.yml

**Summary:**  
Fixed public, private and no-cache directive handling in Cache-Control behavior
Fixes #670 
/claim #670 
**Checklist:**

Fix: Cache-Control header cacheability handling

---

src/blueprint/from_config/definitions.rs
src/blueprint/from_config/from_config.rs
src/blueprint/from_config/mod.rs
src/blueprint/from_config/operators/const_field.rs
src/blueprint/from_config/operators/http.rs

**Summary:**  
Remove duplicate code introduced in https://github.com/tailcallhq/tailcall/pull/640
**Checklist:**

refactor: remove duplicate code

---

src/http/http_1.rs
src/http/http_2.rs
src/http/mod.rs
src/http/request_handler.rs
tests/http_spec.rs

**Summary:**  
Removes unneeded code for the batch vs single request logic. Replaces the two functions that look almost identical with one function that takes in a generic parameter.
None
**Checklist:**

simplifies the request handling for single vs batch request

---

src/cli/command.rs
src/cli/tc.rs
src/config/config.rs
src/config/from_document.rs
src/config/server.rs
src/http/data_loader.rs
tests/http_spec.rs
tests/server_spec.rs

fix: configuration merge error

---

.github/workflows/bot.yml

**Summary:**  
- Removed nginx setup in `bot.yml`
Fixes #724
/claim #724

chore: removed nginx setup

---

.github/workflows/build-website.yml
docs/guides/cli.md
docs/guides/context.md
docs/guides/n+1.md
docs/guides/operator-composition.md
docs/operators/add-field.md
docs/operators/cache.md
docs/operators/const.md
docs/operators/graphql.md
docs/operators/http.md
docs/operators/index.md
docs/operators/modify.md
docs/operators/server.md
docs/operators/upstream.md

**Summary:**  
Just copied over more updated docs from the website repo.

feat: syncing updated docs

---

.graphqlrc.yml
tests/graphql_spec.graphql

**Summary:**  
A little improvement for contributor experience
**Checklist:**

chore: add graphql definitions for directives used in repo tests

---

.github/labels.json
.github/workflows/labels.yml

**Summary:**  
_Github Labels in CI_
Fixes #816
**Checklist:**
/claim #816
Labels Created - https://github.com/Dhanus3133/tailcall/labels (fork)

feat: gh actions label

---

.github/workflows/pr-convention.yml
src/cli/tc.rs

fix(cli/init): handle some edge cases for init command

---

Cargo.lock
Cargo.toml

Reverts tailcallhq/tailcall#946

Revert "fix(deps): update rust crate hyper-rustls to 0.26.0"

---

.github/workflows/ci.yml
src/blueprint/blueprint.rs

fix: auto release

---

Cargo.lock
Cargo.toml
src/auth/jwt/jwks.rs
src/auth/jwt/jwks_remote.rs
src/auth/jwt/jwt_verify.rs
src/blueprint/from_config/auth.rs

fix(cf): added jwt support for wasm

---

Cargo.lock
cloudflare/Cargo.toml
cloudflare/src/file.rs
cloudflare/src/handle.rs
cloudflare/src/http.rs
src/auth/basic.rs
src/http/request_handler.rs

feat(cf): dynamic config loading

---

Cargo.lock

**Summary:**  
Update h2 dependency version in lock file
**Checklist:**

chore: security updates

---

Cargo.lock
cloudflare/Cargo.toml
cloudflare/src/lib.rs

chore(cf): add console panic hook

---

cloudflare/src/handle.rs

chore(cf): fix error string

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/comment-commit.yml
.github/workflows/lint.yml
.github/workflows/pr-convention.yml
src/blueprint/operators/grpc.rs

ci: fix commit comments, pr title validation and autofix

---

.github/workflows/lint.yml
lint.sh

Temporary fix until a more permanent version is available that allows us to leverage nightly features.

chore: remove nightly

---

tests/http_spec.rs

chore: drop is grpc check from http_spec

---

tests/execution/batching-nested-expr.md
tests/snapshots/execution_spec__batching-nested-expr.md_assert_0.snap
tests/snapshots/execution_spec__batching-nested-expr.md_client.snap
tests/snapshots/execution_spec__batching-nested-expr.md_merged.snap

**Summary:**  
Test case for batching request usage inside an expression
**Checklist:**

test: add test case for batching inside an expr

---

.github/workflows/ci.yml

chore: ci release builds

---

src/app_context.rs
src/lambda/modify.rs

refactor: simplify expression modify

---

benches/data_loader_bench.rs
benches/impl_path_string_for_evaluation_context.rs
src/app_context.rs
src/graphql/data_loader.rs
src/grpc/data_loader.rs
src/grpc/request.rs
src/http/data_loader.rs
src/http/request_context.rs
src/lambda/cache.rs
src/lambda/evaluation_context.rs
src/lambda/io.rs
src/path.rs

chore: replace *IO to TargetRuntime

---

src/cli/runtime/mod.rs

chore: fix musl build

---

benches/impl_path_string_for_evaluation_context.rs
src/blueprint/definitions.rs
src/blueprint/from_config.rs
src/blueprint/operators/const_field.rs
src/blueprint/operators/expr.rs
src/blueprint/operators/grpc.rs
src/blueprint/operators/http.rs
src/blueprint/server.rs
src/cli/server/server.rs
src/cli/tc.rs
src/config/reader.rs
src/grpc/data_loader_request.rs
src/http/request_context.rs

chore: rename `config_set` to `config_module`

---

src/app_context.rs
src/blueprint/blueprint.rs
src/blueprint/compress.rs
src/blueprint/definitions.rs
src/blueprint/from_config.rs
src/blueprint/into_schema.rs

chore: lint fixes in `Definition`

---

src/http/request_template.rs
src/mustache.rs

fixes https://github.com/tailcallhq/tailcall/issues/1193

fix: mustache parsing for jsonlike string

---

Cargo.lock
Cargo.toml
cloudflare/Cargo.toml
src/document.rs
src/graphql/request_template.rs
tests/execution/graphql-datasource-mutation.md

**Summary:**  
Upgrade packages
**Checklist:**

chore: upgrade async-graphql

---

src/blueprint/dynamic_value.rs
src/serde_value_ext.rs

**Summary:**  
Small refactor over https://github.com/tailcallhq/tailcall/pull/1196
**Checklist:**

refactor: const with mustache meskill

---

ci-benchmark/benchmark.graphql

chore: disable http cache in benchmarks

---

src/cli/command.rs
src/cli/update_checker.rs

refactor: reuse `Version` variable in update checker

---

src/cli/error.rs
src/cli/tc.rs
src/main.rs

**Summary:**  
/claim #1275
/fixes #1275
**Checklist:**

fix: enhanced server errors

---

tests/execution_spec.md

**Summary:**  
added maintenance section to execution_spec.md
**Checklist:**

chore: update execution_spec.md

---

Cargo.lock
Cargo.toml
cloudflare/Cargo.toml

fix: remove redundant fork of async-graphql

---

src/config/server.rs
src/config/upstream.rs
src/lib.rs
src/merge_right.rs
src/primitive.rs
tests/execution/test-merge-right-with-link-config.md
tests/snapshots/execution_spec__test-merge-right-with-link-config.md_client.snap
tests/snapshots/execution_spec__test-merge-right-with-link-config.md_merged.snap

fix: Specifying @link in config skips upstream.allowedHeaders

---

.codespellignore
.github/workflows/spell-check.yml
src/cli/runtime/http.rs
src/grpc/protobuf.rs
tests/core/snapshots/test-enum-default.md_0.snap
tests/core/snapshots/test-enum-default.md_client.snap
tests/core/snapshots/test-enum-default.md_merged.snap
tests/core/snapshots/test-scalars.md_0.snap
tests/execution/test-enum-default.md
tests/execution/test-scalars.md

chore: spell check fixes

---

generated/.tailcallrc.schema.json
src/blueprint/definitions.rs
src/config/config.rs
src/config/config_module.rs
src/config/from_document.rs
src/config/into_document.rs
tests/core/snapshots/test-interface-from-json.md_client.snap
tests/core/snapshots/test-interface-from-json.md_merged.snap
tests/execution/test-interface-from-json.md

refactor(config): remove explicit interface flag

---

generated/.tailcallrc.schema.json
src/blueprint/definitions.rs
src/blueprint/from_config.rs
src/blueprint/into_schema.rs
src/blueprint/schema.rs
src/config/config.rs
src/config/from_document.rs
src/config/into_document.rs
src/config/source.rs
src/document.rs
src/generator/from_proto.rs
src/generator/snapshots/tailcall__generator__from_proto__test__from_proto.snap
tailcall-cloudflare/package-lock.json
tests/core/snapshots/execution_spec__test-enum-empty.md_errors.snap
tests/core/snapshots/test-enum-description.md_0.snap
tests/core/snapshots/test-enum-description.md_1.snap
tests/core/snapshots/test-enum-description.md_2.snap
tests/core/snapshots/test-enum-description.md_client.snap
tests/core/snapshots/test-enum-description.md_merged.snap
tests/core/spec.rs
tests/execution/test-enum-empty.md

**Summary:**  
Close #1854 
/claim #1854 
**Checklist:**

refactor: drop type variants

---

generated/.tailcallrc.schema.json
src/core/blueprint/from_config.rs
src/core/json/json_schema.rs
tests/core/snapshots/grpc-simple.md_client.snap
tests/core/snapshots/grpc-simple.md_merged.snap
tests/execution/grpc-simple.md

**Summary:**  
Fixes #1899 
**Checklist:**

fix(grpc): empty scalar validation

---

src/core/generator/from_proto.rs
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__from_proto.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__greetings_proto_file.snap

**Summary:**  
Fixes #1898 
**Checklist:**

fix(grpc): add body to generated config

---

src/core/generator/from_proto.rs
src/core/generator/graphql_type.rs
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__nested_types.snap
tailcall-cloudflare/package-lock.json
tailcall-fixtures/fixtures/protobuf/nested_types.proto

**Summary:**  
Fixes #1754 
**Checklist:**

fix(grpc): proper generation for nested message and enum

---

Cargo.lock
src/core/http/request_template.rs
tests/execution/input-type-protected-error.md

perf: parsing constant url at compile time

---

src/core/generator/from_proto.rs

refactor: drop unused GRPCMethod from blueprint

---

Cargo.lock
Cargo.toml
src/core/http/response.rs

perf: using serde borrow value

---

tailcall-aws-lambda/src/http.rs

fix: passing lambda request headers to hyper request

---

src/cli/runtime/mod.rs

fix: windows build

---

src/core/generator/from_json.rs
src/core/generator/snapshots/tailcall__core__generator__generator__test__jsonplaceholder.typicode.com.snap
src/core/generator/snapshots/tailcall__core__generator__generator__test__read_all_with_rest_api_gen.snap
tests/core/snapshots/execution_spec__core__json_to_config_spec__boolean.json.snap

**Summary:**  
- added support for path variables.
Fixes #1996
**Checklist:**

feat: add support for path variables

---

.github/workflows/ci.yml

fix: rquickjs windows build

---

Cargo.lock
Cargo.toml
src/cli/telemetry.rs
tailcall-upstream-grpc/Cargo.toml

chore: upgrade opentelemetry version

---

src/core/generator/from_proto.rs
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__from_proto.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__from_proto_no_pkg_file.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__map_types.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__movies.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__optional_fields.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__required_types.snap
src/core/grpc/protobuf.rs
tailcall-fixtures/fixtures/protobuf/optional.proto

fix(grpc): config generation for optional fields

---

tests/core/snapshots/test-scalars-builtin.md_0.snap
tests/core/snapshots/test-scalars-builtin.md_1.snap
tests/core/snapshots/test-scalars-builtin.md_2.snap
tests/core/snapshots/test-scalars-builtin.md_3.snap
tests/core/snapshots/test-scalars-builtin.md_4.snap
tests/core/snapshots/test-scalars-builtin.md_5.snap
tests/core/snapshots/test-scalars-builtin.md_6.snap
tests/core/snapshots/test-scalars-builtin.md_7.snap
tests/core/snapshots/test-scalars-builtin.md_8.snap
tests/core/snapshots/test-scalars-builtin.md_9.snap
tests/core/snapshots/test-scalars-builtin.md_client.snap
tests/core/snapshots/test-scalars-builtin.md_merged.snap
tests/execution/test-scalars-builtin.md

test: missing builtin scalar validation

---

.github/workflows/ci.yml

**Summary:**  
Notify ci failure on discord
/claim #2073
Fixes #2073

chore: notify ci failure on Discord

---

tests/core/snapshots/test-scalars-validation.md_0.snap
tests/core/snapshots/test-scalars-validation.md_1.snap
tests/core/snapshots/test-scalars-validation.md_client.snap
tests/core/snapshots/test-scalars-validation.md_merged.snap
tests/execution/test-scalars-validation.md

test: scalar validation as input and output type

---

tests/core/snapshots/test-expr-scalar-as-string.md_0.snap
tests/core/snapshots/test-expr-scalar-as-string.md_client.snap
tests/core/snapshots/test-expr-scalar-as-string.md_merged.snap
tests/execution/test-expr-scalar-as-string.md

test: @expr converts string to other primitive value

---

benches/data_loader_bench.rs
src/core/graphql/request_template.rs
src/core/grpc/request_template.rs
src/core/http/request_context.rs
src/core/http/request_template.rs
src/core/ir/cache.rs
src/core/ir/io.rs
src/core/mod.rs
src/core/runtime.rs
tailcall-cloudflare/src/cache.rs
tailcall-cloudflare/src/runtime.rs

chore: add IO_ID in caches

---

src/core/ir/jit/builder.rs
src/core/ir/jit/model.rs
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__fragments.snap
src/core/ir/jit/store.rs

fix: fragments test

---

src/core/ir/jit/builder.rs
src/core/ir/jit/context.rs
src/core/ir/jit/execute.rs
src/core/ir/jit/model.rs
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__default_value.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__fragments.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__from_document.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__multiple_operations.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_mutation.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_query.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__unions.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__variables.snap
src/core/ir/jit/synth.rs

chore(QP): store Vec<Field<Children>> in edoc

---

Cargo.lock
Cargo.toml
src/core/counter.rs
src/core/generator/json/mod.rs
src/core/ir/jit/builder.rs
src/core/ir/jit/context.rs
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__default_value.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__fragments.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__from_document.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__multiple_operations.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_mutation.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_query.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__unions.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__variables.snap
src/core/ir/jit/synth.rs
src/core/ir/mod.rs

chore: replace IoId with CallId

---

src/core/blueprint/operators/http.rs
tests/core/snapshots/recursive-type.md_client.snap
tests/core/snapshots/recursive-type.md_merged.snap
tests/execution/recursive-type.md

fix: removing input and output schema from Endpoint

---

src/core/ir/jit/fixtures/jsonplaceholder-mutation.graphql
src/core/ir/jit/snapshots/tailcall__core__ir__jit__synth__tests__synth.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__synth__tests__synth_all_posts_users.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__synth__tests__synth_all_posts_users_todos.snap
src/core/ir/jit/store.rs
src/core/ir/jit/synth.rs

chore(store): drop struct Data

---

src/core/ir/cache.rs
src/core/ir/eval.rs
src/core/ir/jit/execute.rs
src/core/ir/jit/fixtures/jsonplaceholder-mutation.graphql
src/core/ir/jit/helper.rs
src/core/ir/jit/mod.rs
src/core/ir/jit/synth.rs
src/core/ir/mod.rs

[stack]: rewrite GraphQL engine - 1

---

src/core/ir/io.rs

chore: remove key cloning for cache

---

src/core/ir/jit/context.rs
src/core/ir/jit/execute.rs
src/core/ir/jit/snapshots/tailcall__core__ir__jit__context__tests__foo.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__context__tests__nested.snap

[stack]: rewrite GraphQL engine - Implement ExecutionContext

---

benches/impl_path_string_for_evaluation_context.rs
src/core/blueprint/into_schema.rs
src/core/has_headers.rs
src/core/ir/cache.rs
src/core/ir/eval.rs
src/core/ir/evaluation_context.rs
src/core/ir/io.rs
src/core/ir/mod.rs
src/core/ir/resolver_context_like.rs
src/core/path.rs
tailcall-query-plan/src/execution/executor.rs
tailcall-query-plan/src/resolver.rs
tests/expression_spec.rs

**Summary:**  
Remove unnecessary restrictions and explicit lifetimes where possible.
**Checklist:**

refactor: simplify Eval trait

---

Cargo.lock
Cargo.toml
src/core/blueprint/blueprint.rs
src/core/counter.rs
src/core/generator/json/mod.rs
src/core/ir/jit/blueprint_index.rs
src/core/ir/jit/builder.rs
src/core/ir/jit/fixtures/jsonplaceholder-mutation.graphql
src/core/ir/jit/mod.rs
src/core/ir/jit/model.rs
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__default_value.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__fragments.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__from_document.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__multiple_operations.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_mutation.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__simple_query.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__unions.snap
src/core/ir/jit/snapshots/tailcall__core__ir__jit__builder__tests__variables.snap
src/core/ir/mod.rs

- **add blueprint_index and model**
- **add tests for plan generation**

refactor: add models for JIT

---

src/core/config/config.rs
src/core/config/transformer/ambiguous_type.rs
src/core/config/transformer/snapshots/tailcall__core__config__transformer__ambiguous_type__tests__resolve_ambiguous_news_types.snap
src/core/config/transformer/snapshots/tailcall__core__config__transformer__ambiguous_type__tests__resolve_ambiguous_types.snap
src/core/generator/snapshots/tailcall__core__generator__from_proto__test__movies.snap

**Summary:**  
Fixes #2227
**Checklist:**

fix: do not mark enums and scalars as input types

---

src/core/ir/eval_context.rs
tests/core/snapshots/test-input-with-arg-out.md_0.snap
tests/core/snapshots/test-input-with-arg-out.md_client.snap
tests/core/snapshots/test-input-with-arg-out.md_merged.snap
tests/execution/test-input-with-arg-out.md

**Summary:**  
Fixes #2244 
- [ X] I ran `cargo test` successfully.
- [ X] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.
**Checklist:**
- [ x] I have added relevant unit & integration tests.
- [x ] I have performed a self-review of my code.
- [ x] PR follows the naming convention of `<type>(<optional scope>): <title>`

fix: nested args

---

src/core/config/config_module.rs
src/core/config/into_document.rs
src/core/config/transformer/mod.rs
src/core/config/transformer/nested_unions.rs
src/core/config/transformer/snapshots/tailcall__core__config__transformer__nested_unions__tests__nested_unions.snap
src/core/config/transformer/snapshots/tailcall__core__config__transformer__nested_unions__tests__nested_unions_recursive.snap
tailcall-fixtures/fixtures/configs/yaml-nested-unions-recursive.yaml
tests/core/snapshots/yaml-nested-unions.md_client.snap
tests/core/snapshots/yaml-nested-unions.md_merged.snap

fix: nested unions

---

src/core/ir/jit/store.rs
src/core/ir/jit/synth.rs

refactor: make store polymorphic

---

Cargo.lock
Cargo.toml
benches/handle_request_bench.rs
src/cli/server/http_server.rs
src/cli/tc.rs
src/core/blueprint/auth.rs
src/core/blueprint/definitions.rs
src/core/blueprint/operators/call.rs
src/core/blueprint/operators/grpc.rs
src/core/blueprint/operators/js.rs
src/core/blueprint/operators/protected.rs
src/core/blueprint/server.rs
src/core/blueprint/upstream.rs
src/core/config/config_module.rs
src/core/config/into_document.rs
src/core/config/reader.rs
src/core/config/transformer/ambiguous_type.rs
src/core/generator/generator.rs
src/core/generator/tests/json_to_config_spec.rs
src/core/grpc/data_loader_request.rs
src/core/grpc/protobuf.rs
src/core/grpc/request_template.rs
tailcall-aws-lambda/src/main.rs
tests/core/parse.rs

Reverts tailcallhq/tailcall#2263

Revert "chore: dropped pub fields from config module"

---

src/core/document.rs

**Summary:**  
fixes inner directive that contains  quoted string 
**Checklist:**

fix: inner directives String

---

src/core/config/config.rs
src/core/config/config_module.rs
src/core/config/into_document.rs

fix: drop `to_sdl` from `ConfigModule`

---

src/core/data_loader/dedupe.rs
src/core/mod.rs

**Summary:**  
Fixes #2276
**Checklist:**

fix: dedupe dead-lock on dropped requests

---

.github/workflows/build_matrix.yml
npm/gen-root.ts

fix: ci npm publish

---

src/core/http/data_loader.rs
tests/execution/batching-default.md
tests/execution/batching-group-by-default.md
tests/execution/batching-group-by.md

**Summary:**  
Non batch keys should not be duplicated. relevant integration tests have been fixed too.
**Checklist:**

fix: remove repeated non batch key

---

src/core/jit/builder.rs
src/core/jit/snapshots/tailcall__core__jit__builder__tests__fragments.snap
tests/jit_spec.rs
tests/snapshots/jit_spec__tests__executor_fragments.snap
tests/snapshots/jit_spec__tests__executor_fragments_nested.snap

fix: query plan fragments

---

src/core/blueprint/operators/call.rs
tests/core/snapshots/call-graphql-datasource.md_client.snap
tests/core/snapshots/call-mutation.md_client.snap
tests/core/snapshots/call-operator.md_client.snap
tests/core/snapshots/jsonplaceholder-call-post.md_client.snap

fix: call operator changes list of arguments

---

.github/labels.json

ci: fix labels.json

---

src/core/jit/common/json_placeholder.rs
src/core/jit/exec.rs
src/core/jit/synth/synth_const.rs
src/core/json/borrow.rs
src/core/json/graphql.rs
src/core/json/json_like.rs
src/core/json/mod.rs
src/core/json/serde.rs
src/core/scalar/bytes.rs
src/core/scalar/date.rs
src/core/scalar/email.rs
src/core/scalar/phone.rs
src/core/scalar/url.rs

refactor: JsonLike return an Option instead of Result

---

src/core/jit/builder.rs
src/core/jit/error.rs
src/core/jit/exec.rs
src/core/jit/model.rs
src/core/jit/response.rs
src/core/jit/synth/synth_const.rs

fix(jit): positioned and extensions info for errors

---

Cargo.lock
Cargo.toml
src/core/blueprint/into_schema.rs
src/core/scalar/bytes.rs
src/core/scalar/date.rs
src/core/scalar/email.rs
src/core/scalar/empty.rs
src/core/scalar/int128.rs
src/core/scalar/int16.rs
src/core/scalar/int32.rs
src/core/scalar/int64.rs
src/core/scalar/int8.rs
src/core/scalar/json.rs
src/core/scalar/mod.rs
src/core/scalar/phone.rs
src/core/scalar/uint128.rs
src/core/scalar/uint16.rs
src/core/scalar/uint32.rs
src/core/scalar/uint64.rs
src/core/scalar/uint8.rs
src/core/scalar/url.rs
tailcall-typedefs/src/main.rs

chore: make `validate` function generic in `Scalar` trait

---

src/core/jit/error.rs
src/core/jit/graphql_executor.rs
src/core/jit/response.rs

fix(jit): handle parsing/build errors

---

src/core/http/query_encoder.rs
src/core/http/request_template.rs
tests/core/snapshots/batching-group-by-optional-key.md_0.snap
tests/core/snapshots/batching-group-by-optional-key.md_client.snap
tests/core/snapshots/batching-group-by-optional-key.md_merged.snap
tests/execution/batching-group-by-optional-key.md
tests/execution/nullable-arg-query.md

fix: pick query params with empty values

---

src/cli/generator/snapshots/tailcall__cli__generator__generator__test__generator_spec__src__cli__generator__tests__fixtures__generator__jsonplaceholder.json.snap
src/core/config/transformer/improve_type_names.rs

**Summary:**  
/claim #2486
fixes #2486 
**Checklist:**

fix: save singularized candidate name

---

src/core/document.rs
src/core/ir/resolver_context_like.rs
src/core/jit/model.rs

chore: drop directive adapter trait

---

src/core/jit/error.rs
src/core/jit/exec.rs
src/core/jit/graphql_executor.rs
src/core/jit/model.rs
src/core/jit/response.rs
src/core/jit/synth/mod.rs
src/core/jit/synth/synth_const.rs

fix(jit): handle error path and position in single place

---

src/core/blueprint/blueprint.rs
src/core/blueprint/definitions.rs
src/core/blueprint/into_schema.rs
src/core/jit/synth/synth.rs
src/core/scalar/bytes.rs
src/core/scalar/date.rs
src/core/scalar/email.rs
src/core/scalar/empty.rs
src/core/scalar/int128.rs
src/core/scalar/int16.rs
src/core/scalar/int32.rs
src/core/scalar/int64.rs
src/core/scalar/int8.rs
src/core/scalar/json.rs
src/core/scalar/mod.rs
src/core/scalar/phone.rs
src/core/scalar/uint128.rs
src/core/scalar/uint16.rs
src/core/scalar/uint32.rs
src/core/scalar/uint64.rs
src/core/scalar/uint8.rs
src/core/scalar/url.rs

some HTRB blunders are fixed here..
**TODO**
~~- [ ] drop JsonLikeOwned from Scalar~~

chore: drop HRTB from `Synth`

---

src/core/jit/context.rs
src/core/jit/error.rs
src/core/jit/exec.rs
src/core/jit/model.rs
src/core/jit/response.rs

chore: fix graphql error test cases for JIT

---

Cargo.lock
Cargo.toml
src/cli/server/http_server.rs
src/core/blueprint/from_config.rs

chore: log blueprint gen time

---

src/core/jit/context.rs
src/core/jit/exec.rs

**Summary:**  
See discussion https://github.com/tailcallhq/tailcall/pull/2522#discussion_r1692987543 for references
**Checklist:**

fix(jit): nested resolvers for IR and non-IR cases

---

src/cli/generator/config.rs
src/core/config/transformer/preset.rs

feat: support `unwrapSingleFieldTypes` via Preset

---

.github/workflows/ci.yml
src/core/proto_reader/fetch.rs

fix: reflection should use HTTP2

---

src/core/generator/json/http_directive_generator.rs
src/core/generator/json/snapshots/tailcall__core__generator__json__query_generator__test__query_generator_with_query_params.snap
src/core/generator/tests/snapshots/json_to_config_spec__number.json.snap

**Summary:**  
Fixes #2559
/claim #2559
**Checklist:**

fix: generate query params in camel case

---

src/core/jit/common/jp.rs
src/core/jit/exec.rs
src/core/jit/synth/synth.rs
src/core/json/borrow.rs
src/core/json/graphql.rs
src/core/json/json_like.rs
src/core/json/mod.rs
src/core/json/serde.rs

refactor(json): relax json_like trait lifetimes

---

src/core/fixtures/helloworld.graphql
src/core/mod.rs
src/core/snapshots/tailcall__core__tests__include_config.snap

chore: introduce include_config

---

src/cli/generator/config.rs

fix: deny unknown fields in config

---

src/core/blueprint/fixture/all-constructs.graphql
src/core/blueprint/index.rs
src/core/blueprint/snapshots/tailcall__core__blueprint__index__test__from_blueprint.snap
src/core/jit/context.rs
src/core/jit/response.rs
src/core/jit/snapshots/tailcall__core__jit__response__test__adding_errors.snap
src/core/jit/snapshots/tailcall__core__jit__response__test__conversion_to_async_graphql.snap
src/core/jit/snapshots/tailcall__core__jit__response__test__with_error-2.snap
src/core/jit/snapshots/tailcall__core__jit__response__test__with_error.snap

chore: improve test coverage for jit

---

src/core/ir/resolver_context_like.rs
src/core/jit/builder.rs
src/core/jit/model.rs
src/core/jit/snapshots/tailcall__core__jit__builder__tests__alias_query.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__default_value.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__directives.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__fragments.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__from_document.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__multiple_operations.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__resolving_operation-2.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__resolving_operation.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__simple_mutation.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__simple_query.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__unions.snap
src/core/jit/snapshots/tailcall__core__jit__builder__tests__variables.snap
src/core/jit/synth/snapshots/tailcall__core__jit__synth__synth__tests__json_placeholder_typename.snap
src/core/jit/synth/synth.rs

fix(jit): resolve __typename for values

---

src/core/config/server.rs

feat: enable JIT by default for all requests

---

src/core/generator/tests/snapshots/json_to_config_spec__null.json.snap
src/core/helpers/gql_type.rs

fix: treat null responses as JSON scalars

---

src/cli/javascript/runtime.rs

fix: onRequest returns No such file or directory

---

src/core/http/request_handler.rs

**Summary:**  
Fixes #2855
**Checklist:**

feat: add health check endpoint

---

generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/cli/server/mod.rs
src/core/blueprint/server.rs
src/core/config/server.rs
src/core/http/request_handler.rs
tests/core/snapshots/routes-param-on-server-directive.md_0.snap
tests/core/snapshots/routes-param-on-server-directive.md_1.snap
tests/core/snapshots/routes-param-on-server-directive.md_client.snap
tests/core/snapshots/routes-param-on-server-directive.md_merged.snap
tests/execution/routes-param-on-server-directive.md

**Summary:**  
Fixes #2869
**Checklist:**

feat: make health and graphql endpoints to be configurable

---

src/core/config/from_document.rs
tests/core/snapshots/test-invalid-add-field.md_error.snap
tests/execution/test-invalid-add-field.md

fix: Incorrect Field Path Specification in `@addfield`

---

src/core/path.rs
tests/core/snapshots/enum-args.md_0.snap
tests/core/snapshots/enum-args.md_client.snap
tests/core/snapshots/enum-args.md_merged.snap
tests/execution/enum-args.md

fix(2958): fix unhandled enum in convert_value

---

src/core/jit/synth/synth.rs
tests/core/snapshots/jit-enum-array.md_0.snap
tests/core/snapshots/jit-enum-array.md_client.snap
tests/core/snapshots/jit-enum-array.md_merged.snap
tests/execution/jit-enum-array.md

**Summary:**  
Fix bug that fails to validate an array of enumerations when JIT is enabled
Fixes https://github.com/tailcallhq/tailcall/issues/2959
**Checklist:**

fix(jit): enumerations array validation

---

generated/.tailcallrc.graphql
generated/.tailcallrc.schema.json
src/core/blueprint/dynamic_value.rs
src/core/blueprint/operators/grpc.rs
src/core/blueprint/operators/http.rs
src/core/blueprint/operators/mod.rs
src/core/blueprint/operators/select.rs
src/core/config/directives/grpc.rs
src/core/config/directives/http.rs
src/core/generator/from_proto.rs
src/core/mustache/model.rs
tests/core/snapshots/http-select.md_0.snap
tests/core/snapshots/http-select.md_client.snap
tests/core/snapshots/http-select.md_merged.snap
tests/execution/http-select.md

**Summary:**  
feat: add a select field on HTTP and gRPC
Fixes https://github.com/tailcallhq/tailcall/issues/2956
**Checklist:**

feat: add a select field on HTTP and gRPC

---

generated/.tailcallrc.schema.json
src/core/config/config.rs
src/core/config/config_module/merge.rs
src/core/config/from_document.rs
src/core/config/into_document.rs
src/core/config/transformer/subgraph.rs
tests/core/snapshots/apollo-federation-entities-batch.md_1.snap
tests/core/snapshots/apollo-federation-entities.md_1.snap

fix(federation): output key directive to entity sdl

---

generated/.tailcallrc.graphql
src/core/config/config.rs

fix: `DateTime` is not autogenerated in `.tailcallrc.graphql`

---

src/core/http/query_encoder.rs
tests/core/snapshots/test-enum-as-argument.md_0.snap
tests/core/snapshots/test-enum-as-argument.md_client.snap
tests/core/snapshots/test-enum-as-argument.md_merged.snap
tests/execution/test-enum-as-argument.md

**Summary:**  
Fixes #2990
**Checklist:**

fix: add support for enum args in query encoder

---

src/cli/tc/init.rs

fix:  incomplete .graphqlrc.yml

---

src/cli/tc/helpers.rs
src/cli/tc/init.rs

**Summary:**  
init command adds only required files
Fixes #3040
/claim #3040
**Checklist:**

fix(3040): init should add only the required files according to the selection

---

src/core/app_context.rs
src/core/jit/exec_const.rs
src/core/jit/graphql_executor.rs
src/core/jit/server_error.rs

fix: cache const response

---

src/core/jit/graphql_executor.rs
src/core/jit/model.rs
src/core/jit/request.rs
src/core/jit/transform/check_protected.rs
src/core/jit/transform/input_resolver.rs
src/core/jit/transform/mod.rs

fix: don't cache if plan is protected.

---

tailcall-tracker/src/dispatch.rs

refactor: fix file read operation

---

src/core/config/transformer/subgraph.rs
tests/core/snapshots/apollo-federation-validation.md_error.snap
tests/execution/apollo-federation-validation.md

**Summary:**  
/claim #2911
Fixes #2911
**Checklist:**

fix(2911): add validation in federation resolvers

---

src/cli/tc/init.rs

**Summary:**  
Fixes #3114
/claim #3114
**Checklist:**

chore(3114): update rc file contents

---

Cargo.lock
Cargo.toml
src/cli/javascript/codec.rs

chore: upgrade rquickjs version

---

Cargo.lock
Cargo.toml
src/core/cache/error.rs
src/core/rest/error.rs
src/core/worker/error.rs
tailcall-fixtures/error.rs
tailcall-tracker/src/error.rs

chore: upgrade derive_more to v1.0.0

---

src/core/config/transformer/preset.rs

feat: enable infer_type_names by-default

---

Cargo.lock
Cargo.toml

chore: update serde_json_borrow version
